### ISSUE TITLE
The "i3Focused Window" required too much computational power

### ISSUE THREAD

**Issue by prashant111192** [CondensedMilk7/i3blocks#1]
The script to show the focused window takes up too much processing while running.
The difference on my i7 10750H with and without the script is around 17%.

**Comment by prashant111192** [comment]
The script to show the focused window takes up too much processing while running. 
The difference on my i7 10750H with and without the script is around 17%.

**Comment by pridont** [comment]
> The script to show the focused window takes up too much processing while running. The difference on my i7 10750H with and without the script is around 17%.

Yes, you are right. This is why I had it commented out by default. I was looking for a way to make it less power intensive or at least find a better alternative, but nothing worked out. I found that polybar has a very nice active window block by default though. I have switched to that and I'm planning to customize it along the lines of this bar here. Feel free to contribute if you find a solution though!

**Comment by prashant111192** [comment]
Hey, I looked it up and someone just mentioned the command within the block to be run every second instead of a persistent do while. 

https://gist.github.com/mnlwldr/ad3002443ef479e691eb67355944b18c

**Comment by pridont** [comment]
Seems to work, although the feedback speed suffers now. It is probably possible to send a signal from i3 config to this block, to run the script only when the focus of the window changes, but I'll settle for this. Thanks! Closing the issue.
